site_name: MkDocs play

site_name: MkDocs test
edit_uri: edit/master/docs/
site_description: A trial site for MkDocs
site_author: Me
copyright: Copyright &copy; Me, 2017
remote_branch: gh-pages
remote_name: origin

theme: 'material'

markdown_extensions:
    - smarty
    - abbr
    - def_list
    - toc:
        separator: "_"
    - sane_lists

extra:
    version: 1.0
    palette:
      primary: 'indigo'
      accent: 'indigo'
    font:
      text: 'Segoe Print'   # 'Kristen ITC' 'Roboto'
      code: 'Consolas'      # 'Roboto Mono'
    logo: 'cogs.png'        #'ivor24.png'   'logo.svg'
    social:                 # see: http://fontawesome.io/icons/
      - type: 'slack'
        link: 'http://slack.com'
      - type: 'stack-overflow'
        link: 'http://stack-overflow.com'
      - type: 'youtube'
        link: 'http://youtube.com'
      - type: 'telegram'
        link: 'http://telegram.com'
      - type: 'whatsapp'
        link: 'http://whatsapp.com'
      - type: 'comment-o'
        link: 'http://comment.com'
      - type: 'facebook'
        link: 'http://facebook.com'
      - type: 'github'
        link: 'https://github.com'
      - type: 'twitter'
        link: 'https://twitter.com'
      - type: 'linkedin'
        link: 'https://linkedin.com'

pages:
    - Home: index.md
    - Lorem 1: lorem001.md
    - Lorem A:
        - Lorem 2: lorem002.md
        - Lorem 3: lorem003.md
    - Lorem B:
        - Lorem 4: lorem004.md
        - Lorem 5: lorem005.md
        - Lorem C:
            - Lorem 6: lorem006.md
            - Lorem 7: lorem007.md
            - Lorem D:
                - Lorem 8: lorem008.md
                - Lorem 9: lorem009.md
    - Lorem 10: lorem010.md

    - Lorem 1 - 100:
        - Lorem 1  : lorem_1.md
        - Lorem 2  : lorem_2.md
        - Lorem 3  : lorem_3.md
        - Lorem 4  : lorem_4.md
        - Lorem 5  : lorem_5.md
        - Lorem 6  : lorem_6.md
        - Lorem 7  : lorem_7.md
        - Lorem 8  : lorem_8.md
        - Lorem 9  : lorem_9.md
        - Lorem 10 : lorem_10.md
        - Lorem 11 : lorem_11.md
        - Lorem 12 : lorem_12.md
        - Lorem 13 : lorem_13.md
        - Lorem 14 : lorem_14.md
        - Lorem 15 : lorem_15.md
        - Lorem 16 : lorem_16.md
        - Lorem 17 : lorem_17.md
        - Lorem 18 : lorem_18.md
        - Lorem 19 : lorem_19.md
        - Lorem 20 : lorem_20.md
        - Lorem 21 : lorem_21.md
        - Lorem 22 : lorem_22.md
        - Lorem 23 : lorem_23.md
        - Lorem 24 : lorem_24.md
        - Lorem 25 : lorem_25.md
        - Lorem 26 : lorem_26.md
        - Lorem 27 : lorem_27.md
        - Lorem 28 : lorem_28.md
        - Lorem 29 : lorem_29.md
        - Lorem 30 : lorem_30.md
        - Lorem 31 : lorem_31.md
        - Lorem 32 : lorem_32.md
        - Lorem 33 : lorem_33.md
        - Lorem 34 : lorem_34.md
        - Lorem 35 : lorem_35.md
        - Lorem 36 : lorem_36.md
        - Lorem 37 : lorem_37.md
        - Lorem 38 : lorem_38.md
        - Lorem 39 : lorem_39.md
        - Lorem 40 : lorem_40.md
        - Lorem 41 : lorem_41.md
        - Lorem 42 : lorem_42.md
        - Lorem 43 : lorem_43.md
        - Lorem 44 : lorem_44.md
        - Lorem 45 : lorem_45.md
        - Lorem 46 : lorem_46.md
        - Lorem 47 : lorem_47.md
        - Lorem 48 : lorem_48.md
        - Lorem 49 : lorem_49.md
        - Lorem 50 : lorem_50.md
        - Lorem 51 : lorem_51.md
        - Lorem 52 : lorem_52.md
        - Lorem 53 : lorem_53.md
        - Lorem 54 : lorem_54.md
        - Lorem 55 : lorem_55.md
        - Lorem 56 : lorem_56.md
        - Lorem 57 : lorem_57.md
        - Lorem 58 : lorem_58.md
        - Lorem 59 : lorem_59.md
        - Lorem 60 : lorem_60.md
        - Lorem 61 : lorem_61.md
        - Lorem 62 : lorem_62.md
        - Lorem 63 : lorem_63.md
        - Lorem 64 : lorem_64.md
        - Lorem 65 : lorem_65.md
        - Lorem 66 : lorem_66.md
        - Lorem 67 : lorem_67.md
        - Lorem 68 : lorem_68.md
        - Lorem 69 : lorem_69.md
        - Lorem 70 : lorem_70.md
        - Lorem 71 : lorem_71.md
        - Lorem 72 : lorem_72.md
        - Lorem 73 : lorem_73.md
        - Lorem 74 : lorem_74.md
        - Lorem 75 : lorem_75.md
        - Lorem 76 : lorem_76.md
        - Lorem 77 : lorem_77.md
        - Lorem 78 : lorem_78.md
        - Lorem 79 : lorem_79.md
        - Lorem 80 : lorem_80.md
        - Lorem 81 : lorem_81.md
        - Lorem 82 : lorem_82.md
        - Lorem 83 : lorem_83.md
        - Lorem 84 : lorem_84.md
        - Lorem 85 : lorem_85.md
        - Lorem 86 : lorem_86.md
        - Lorem 87 : lorem_87.md
        - Lorem 88 : lorem_88.md
        - Lorem 89 : lorem_89.md
        - Lorem 90 : lorem_90.md
        - Lorem 91 : lorem_91.md
        - Lorem 92 : lorem_92.md
        - Lorem 93 : lorem_93.md
        - Lorem 94 : lorem_94.md
        - Lorem 95 : lorem_95.md
        - Lorem 96 : lorem_96.md
        - Lorem 97 : lorem_97.md
        - Lorem 98 : lorem_98.md
        - Lorem 99 : lorem_99.md
        - Lorem 100: lorem_100.md
    - Lorem 101 - 200:
        - Lorem 101: lorem_101.md
        - Lorem 102: lorem_102.md
        - Lorem 103: lorem_103.md
        - Lorem 104: lorem_104.md
        - Lorem 105: lorem_105.md
        - Lorem 106: lorem_106.md
        - Lorem 107: lorem_107.md
        - Lorem 108: lorem_108.md
        - Lorem 109: lorem_109.md
        - Lorem 110: lorem_110.md
        - Lorem 111: lorem_111.md
        - Lorem 112: lorem_112.md
        - Lorem 113: lorem_113.md
        - Lorem 114: lorem_114.md
        - Lorem 115: lorem_115.md
        - Lorem 116: lorem_116.md
        - Lorem 117: lorem_117.md
        - Lorem 118: lorem_118.md
        - Lorem 119: lorem_119.md
        - Lorem 120: lorem_120.md
        - Lorem 121: lorem_121.md
        - Lorem 122: lorem_122.md
        - Lorem 123: lorem_123.md
        - Lorem 124: lorem_124.md
        - Lorem 125: lorem_125.md
        - Lorem 126: lorem_126.md
        - Lorem 127: lorem_127.md
        - Lorem 128: lorem_128.md
        - Lorem 129: lorem_129.md
        - Lorem 130: lorem_130.md
        - Lorem 131: lorem_131.md
        - Lorem 132: lorem_132.md
        - Lorem 133: lorem_133.md
        - Lorem 134: lorem_134.md
        - Lorem 135: lorem_135.md
        - Lorem 136: lorem_136.md
        - Lorem 137: lorem_137.md
        - Lorem 138: lorem_138.md
        - Lorem 139: lorem_139.md
        - Lorem 140: lorem_140.md
        - Lorem 141: lorem_141.md
        - Lorem 142: lorem_142.md
        - Lorem 143: lorem_143.md
        - Lorem 144: lorem_144.md
        - Lorem 145: lorem_145.md
        - Lorem 146: lorem_146.md
        - Lorem 147: lorem_147.md
        - Lorem 148: lorem_148.md
        - Lorem 149: lorem_149.md
        - Lorem 150: lorem_150.md
        - Lorem 151: lorem_151.md
        - Lorem 152: lorem_152.md
        - Lorem 153: lorem_153.md
        - Lorem 154: lorem_154.md
        - Lorem 155: lorem_155.md
        - Lorem 156: lorem_156.md
        - Lorem 157: lorem_157.md
        - Lorem 158: lorem_158.md
        - Lorem 159: lorem_159.md
        - Lorem 160: lorem_160.md
        - Lorem 161: lorem_161.md
        - Lorem 162: lorem_162.md
        - Lorem 163: lorem_163.md
        - Lorem 164: lorem_164.md
        - Lorem 165: lorem_165.md
        - Lorem 166: lorem_166.md
        - Lorem 167: lorem_167.md
        - Lorem 168: lorem_168.md
        - Lorem 169: lorem_169.md
        - Lorem 170: lorem_170.md
        - Lorem 171: lorem_171.md
        - Lorem 172: lorem_172.md
        - Lorem 173: lorem_173.md
        - Lorem 174: lorem_174.md
        - Lorem 175: lorem_175.md
        - Lorem 176: lorem_176.md
        - Lorem 177: lorem_177.md
        - Lorem 178: lorem_178.md
        - Lorem 179: lorem_179.md
        - Lorem 180: lorem_180.md
        - Lorem 181: lorem_181.md
        - Lorem 182: lorem_182.md
        - Lorem 183: lorem_183.md
        - Lorem 184: lorem_184.md
        - Lorem 185: lorem_185.md
        - Lorem 186: lorem_186.md
        - Lorem 187: lorem_187.md
        - Lorem 188: lorem_188.md
        - Lorem 189: lorem_189.md
        - Lorem 190: lorem_190.md
        - Lorem 191: lorem_191.md
        - Lorem 192: lorem_192.md
        - Lorem 193: lorem_193.md
        - Lorem 194: lorem_194.md
        - Lorem 195: lorem_195.md
        - Lorem 196: lorem_196.md
        - Lorem 197: lorem_197.md
        - Lorem 198: lorem_198.md
        - Lorem 199: lorem_199.md
        - Lorem 200: lorem_200.md
    - Lorem 201 - 300:
        - Lorem 201: lorem_201.md
        - Lorem 202: lorem_202.md
        - Lorem 203: lorem_203.md
        - Lorem 204: lorem_204.md
        - Lorem 205: lorem_205.md
        - Lorem 206: lorem_206.md
        - Lorem 207: lorem_207.md
        - Lorem 208: lorem_208.md
        - Lorem 209: lorem_209.md
        - Lorem 210: lorem_210.md
        - Lorem 211: lorem_211.md
        - Lorem 212: lorem_212.md
        - Lorem 213: lorem_213.md
        - Lorem 214: lorem_214.md
        - Lorem 215: lorem_215.md
        - Lorem 216: lorem_216.md
        - Lorem 217: lorem_217.md
        - Lorem 218: lorem_218.md
        - Lorem 219: lorem_219.md
        - Lorem 220: lorem_220.md
        - Lorem 221: lorem_221.md
        - Lorem 222: lorem_222.md
        - Lorem 223: lorem_223.md
        - Lorem 224: lorem_224.md
        - Lorem 225: lorem_225.md
        - Lorem 226: lorem_226.md
        - Lorem 227: lorem_227.md
        - Lorem 228: lorem_228.md
        - Lorem 229: lorem_229.md
        - Lorem 230: lorem_230.md
        - Lorem 231: lorem_231.md
        - Lorem 232: lorem_232.md
        - Lorem 233: lorem_233.md
        - Lorem 234: lorem_234.md
        - Lorem 235: lorem_235.md
        - Lorem 236: lorem_236.md
        - Lorem 237: lorem_237.md
        - Lorem 238: lorem_238.md
        - Lorem 239: lorem_239.md
        - Lorem 240: lorem_240.md
        - Lorem 241: lorem_241.md
        - Lorem 242: lorem_242.md
        - Lorem 243: lorem_243.md
        - Lorem 244: lorem_244.md
        - Lorem 245: lorem_245.md
        - Lorem 246: lorem_246.md
        - Lorem 247: lorem_247.md
        - Lorem 248: lorem_248.md
        - Lorem 249: lorem_249.md
        - Lorem 250: lorem_250.md
        - Lorem 251: lorem_251.md
        - Lorem 252: lorem_252.md
        - Lorem 253: lorem_253.md
        - Lorem 254: lorem_254.md
        - Lorem 255: lorem_255.md
        - Lorem 256: lorem_256.md
        - Lorem 257: lorem_257.md
        - Lorem 258: lorem_258.md
        - Lorem 259: lorem_259.md
        - Lorem 260: lorem_260.md
        - Lorem 261: lorem_261.md
        - Lorem 262: lorem_262.md
        - Lorem 263: lorem_263.md
        - Lorem 264: lorem_264.md
        - Lorem 265: lorem_265.md
        - Lorem 266: lorem_266.md
        - Lorem 267: lorem_267.md
        - Lorem 268: lorem_268.md
        - Lorem 269: lorem_269.md
        - Lorem 270: lorem_270.md
        - Lorem 271: lorem_271.md
        - Lorem 272: lorem_272.md
        - Lorem 273: lorem_273.md
        - Lorem 274: lorem_274.md
        - Lorem 275: lorem_275.md
        - Lorem 276: lorem_276.md
        - Lorem 277: lorem_277.md
        - Lorem 278: lorem_278.md
        - Lorem 279: lorem_279.md
        - Lorem 280: lorem_280.md
        - Lorem 281: lorem_281.md
        - Lorem 282: lorem_282.md
        - Lorem 283: lorem_283.md
        - Lorem 284: lorem_284.md
        - Lorem 285: lorem_285.md
        - Lorem 286: lorem_286.md
        - Lorem 287: lorem_287.md
        - Lorem 288: lorem_288.md
        - Lorem 289: lorem_289.md
        - Lorem 290: lorem_290.md
        - Lorem 291: lorem_291.md
        - Lorem 292: lorem_292.md
        - Lorem 293: lorem_293.md
        - Lorem 294: lorem_294.md
        - Lorem 295: lorem_295.md
        - Lorem 296: lorem_296.md
        - Lorem 297: lorem_297.md
        - Lorem 298: lorem_298.md
        - Lorem 299: lorem_299.md
        - Lorem 300: lorem_300.md
    - Lorem 301 - 400:
        - Lorem 301: lorem_301.md
        - Lorem 302: lorem_302.md
        - Lorem 303: lorem_303.md
        - Lorem 304: lorem_304.md
        - Lorem 305: lorem_305.md
        - Lorem 306: lorem_306.md
        - Lorem 307: lorem_307.md
        - Lorem 308: lorem_308.md
        - Lorem 309: lorem_309.md
        - Lorem 310: lorem_310.md
        - Lorem 311: lorem_311.md
        - Lorem 312: lorem_312.md
        - Lorem 313: lorem_313.md
        - Lorem 314: lorem_314.md
        - Lorem 315: lorem_315.md
        - Lorem 316: lorem_316.md
        - Lorem 317: lorem_317.md
        - Lorem 318: lorem_318.md
        - Lorem 319: lorem_319.md
        - Lorem 320: lorem_320.md
        - Lorem 321: lorem_321.md
        - Lorem 322: lorem_322.md
        - Lorem 323: lorem_323.md
        - Lorem 324: lorem_324.md
        - Lorem 325: lorem_325.md
        - Lorem 326: lorem_326.md
        - Lorem 327: lorem_327.md
        - Lorem 328: lorem_328.md
        - Lorem 329: lorem_329.md
        - Lorem 330: lorem_330.md
        - Lorem 331: lorem_331.md
        - Lorem 332: lorem_332.md
        - Lorem 333: lorem_333.md
        - Lorem 334: lorem_334.md
        - Lorem 335: lorem_335.md
        - Lorem 336: lorem_336.md
        - Lorem 337: lorem_337.md
        - Lorem 338: lorem_338.md
        - Lorem 339: lorem_339.md
        - Lorem 340: lorem_340.md
        - Lorem 341: lorem_341.md
        - Lorem 342: lorem_342.md
        - Lorem 343: lorem_343.md
        - Lorem 344: lorem_344.md
        - Lorem 345: lorem_345.md
        - Lorem 346: lorem_346.md
        - Lorem 347: lorem_347.md
        - Lorem 348: lorem_348.md
        - Lorem 349: lorem_349.md
        - Lorem 350: lorem_350.md
        - Lorem 351: lorem_351.md
        - Lorem 352: lorem_352.md
        - Lorem 353: lorem_353.md
        - Lorem 354: lorem_354.md
        - Lorem 355: lorem_355.md
        - Lorem 356: lorem_356.md
        - Lorem 357: lorem_357.md
        - Lorem 358: lorem_358.md
        - Lorem 359: lorem_359.md
        - Lorem 360: lorem_360.md
        - Lorem 361: lorem_361.md
        - Lorem 362: lorem_362.md
        - Lorem 363: lorem_363.md
        - Lorem 364: lorem_364.md
        - Lorem 365: lorem_365.md
        - Lorem 366: lorem_366.md
        - Lorem 367: lorem_367.md
        - Lorem 368: lorem_368.md
        - Lorem 369: lorem_369.md
        - Lorem 370: lorem_370.md
        - Lorem 371: lorem_371.md
        - Lorem 372: lorem_372.md
        - Lorem 373: lorem_373.md
        - Lorem 374: lorem_374.md
        - Lorem 375: lorem_375.md
        - Lorem 376: lorem_376.md
        - Lorem 377: lorem_377.md
        - Lorem 378: lorem_378.md
        - Lorem 379: lorem_379.md
        - Lorem 380: lorem_380.md
        - Lorem 381: lorem_381.md
        - Lorem 382: lorem_382.md
        - Lorem 383: lorem_383.md
        - Lorem 384: lorem_384.md
        - Lorem 385: lorem_385.md
        - Lorem 386: lorem_386.md
        - Lorem 387: lorem_387.md
        - Lorem 388: lorem_388.md
        - Lorem 389: lorem_389.md
        - Lorem 390: lorem_390.md
        - Lorem 391: lorem_391.md
        - Lorem 392: lorem_392.md
        - Lorem 393: lorem_393.md
        - Lorem 394: lorem_394.md
        - Lorem 395: lorem_395.md
        - Lorem 396: lorem_396.md
        - Lorem 397: lorem_397.md
        - Lorem 398: lorem_398.md
        - Lorem 399: lorem_399.md
        - Lorem 400: lorem_400.md
    - Lorem 401 - 500:
        - Lorem 401: lorem_401.md
        - Lorem 402: lorem_402.md
        - Lorem 403: lorem_403.md
        - Lorem 404: lorem_404.md
        - Lorem 405: lorem_405.md
        - Lorem 406: lorem_406.md
        - Lorem 407: lorem_407.md
        - Lorem 408: lorem_408.md
        - Lorem 409: lorem_409.md
        - Lorem 410: lorem_410.md
        - Lorem 411: lorem_411.md
        - Lorem 412: lorem_412.md
        - Lorem 413: lorem_413.md
        - Lorem 414: lorem_414.md
        - Lorem 415: lorem_415.md
        - Lorem 416: lorem_416.md
        - Lorem 417: lorem_417.md
        - Lorem 418: lorem_418.md
        - Lorem 419: lorem_419.md
        - Lorem 420: lorem_420.md
        - Lorem 421: lorem_421.md
        - Lorem 422: lorem_422.md
        - Lorem 423: lorem_423.md
        - Lorem 424: lorem_424.md
        - Lorem 425: lorem_425.md
        - Lorem 426: lorem_426.md
        - Lorem 427: lorem_427.md
        - Lorem 428: lorem_428.md
        - Lorem 429: lorem_429.md
        - Lorem 430: lorem_430.md
        - Lorem 431: lorem_431.md
        - Lorem 432: lorem_432.md
        - Lorem 433: lorem_433.md
        - Lorem 434: lorem_434.md
        - Lorem 435: lorem_435.md
        - Lorem 436: lorem_436.md
        - Lorem 437: lorem_437.md
        - Lorem 438: lorem_438.md
        - Lorem 439: lorem_439.md
        - Lorem 440: lorem_440.md
        - Lorem 441: lorem_441.md
        - Lorem 442: lorem_442.md
        - Lorem 443: lorem_443.md
        - Lorem 444: lorem_444.md
        - Lorem 445: lorem_445.md
        - Lorem 446: lorem_446.md
        - Lorem 447: lorem_447.md
        - Lorem 448: lorem_448.md
        - Lorem 449: lorem_449.md
        - Lorem 450: lorem_450.md
        - Lorem 451: lorem_451.md
        - Lorem 452: lorem_452.md
        - Lorem 453: lorem_453.md
        - Lorem 454: lorem_454.md
        - Lorem 455: lorem_455.md
        - Lorem 456: lorem_456.md
        - Lorem 457: lorem_457.md
        - Lorem 458: lorem_458.md
        - Lorem 459: lorem_459.md
        - Lorem 460: lorem_460.md
        - Lorem 461: lorem_461.md
        - Lorem 462: lorem_462.md
        - Lorem 463: lorem_463.md
        - Lorem 464: lorem_464.md
        - Lorem 465: lorem_465.md
        - Lorem 466: lorem_466.md
        - Lorem 467: lorem_467.md
        - Lorem 468: lorem_468.md
        - Lorem 469: lorem_469.md
        - Lorem 470: lorem_470.md
        - Lorem 471: lorem_471.md
        - Lorem 472: lorem_472.md
        - Lorem 473: lorem_473.md
        - Lorem 474: lorem_474.md
        - Lorem 475: lorem_475.md
        - Lorem 476: lorem_476.md
        - Lorem 477: lorem_477.md
        - Lorem 478: lorem_478.md
        - Lorem 479: lorem_479.md
        - Lorem 480: lorem_480.md
        - Lorem 481: lorem_481.md
        - Lorem 482: lorem_482.md
        - Lorem 483: lorem_483.md
        - Lorem 484: lorem_484.md
        - Lorem 485: lorem_485.md
        - Lorem 486: lorem_486.md
        - Lorem 487: lorem_487.md
        - Lorem 488: lorem_488.md
        - Lorem 489: lorem_489.md
        - Lorem 490: lorem_490.md
        - Lorem 491: lorem_491.md
        - Lorem 492: lorem_492.md
        - Lorem 493: lorem_493.md
        - Lorem 494: lorem_494.md
        - Lorem 495: lorem_495.md
        - Lorem 496: lorem_496.md
        - Lorem 497: lorem_497.md
        - Lorem 498: lorem_498.md
        - Lorem 499: lorem_499.md
        - Lorem 500: lorem_500.md

    - Lorem very long: lorem_verylong.md
    - Other stuff:
        - Pandoc transforms                                          : transforms.md
        - Test tags                                                  : test_tags_190.md
        - MkDocs notes                                               : mkdocs_notes.md

