site_name: MkDocs play

site_name: MkDocs test
edit_uri: edit/master/docs/
site_description: A trial site for MkDocs
site_author: Me
copyright: Copyright &copy; Me, 2017
remote_branch: gh-pages
remote_name: origin

theme: 'material'

markdown_extensions:
    - smarty
    - abbr
    - def_list
    - toc:
        separator: "_"
    - sane_lists

extra:
    version: 1.0
    palette:
      primary: 'indigo'
      accent: 'indigo'
    font:
      text: 'Segoe Print'   # 'Kristen ITC' 'Roboto'
      code: 'Consolas'      # 'Roboto Mono'
    social:                 # see: http://fontawesome.io/icons/
      - type: 'slack'
        link: 'http://slack.com'
      - type: 'stack-overflow'
        link: 'http://stack-overflow.com'
      - type: 'youtube'
        link: 'http://youtube.com'
      - type: 'telegram'
        link: 'http://telegram.com'
      - type: 'whatsapp'
        link: 'http://whatsapp.com'
      - type: 'comment-o'
        link: 'http://comment.com'
      - type: 'facebook'
        link: 'http://facebook.com'
      - type: 'github'
        link: 'https://github.com'
      - type: 'twitter'
        link: 'https://twitter.com'
      - type: 'linkedin'
        link: 'https://linkedin.com'

pages:
    - Home: index.md
    - Lorem 1: lorem001.md
    - Lorem A:
        - Lorem 2: lorem002.md
        - Lorem 3: lorem003.md
    - Lorem B:
        - Lorem 4: lorem004.md
        - Lorem 5: lorem005.md
        - Lorem C:
            - Lorem 6: lorem006.md
            - Lorem 7: lorem007.md
            - Lorem D:
                - Lorem 8: lorem008.md
                - Lorem 9: lorem009.md
    - Lorem 10: lorem010.md

    - Other stuff:
        - Pandoc transforms                                          : transforms.md
        - Test tags                                                  : test_tags_190.md
        - MkDocs notes                                               : mkdocs_notes.md
