site_name: MkDocs test

theme: 'material'

pages:
    - Home: index.md
    - lorum001.md
        - lorum002.md
        - lorum003.md
            - lorum004.md
            - lorum005.md
                - lorum006.md
                - lorum007.md
            - lorum008.md
                - lorum009.md
    - lorum010.md
