site_name: MkDocs play

site_url: https://pmhayward.github.io/mkd-test/
repo_url: https://github.com/pmhayward/mkd-test/
edit_uri: edit/master/docs/

site_description: A trial site for MkDocs
site_author: Peter Hayward
copyright: Copyright &copy; Peter Hayward, 2017
remote_branch: gh-pages
remote_name: origin

theme: 'material'
theme_dir: 'theme'

markdown_extensions:
    - smarty
    - abbr
    - def_list
    - toc
    - sane_lists
    - codehilite(linenums=true)

dev_addr: 127.0.0.1:8080

extra:
    version: 1.0
    palette:
      primary: 'teal' # red, pink, purple, deep purple, indigo, blue, light blue, cyan, teal, green, light green, lime, yellow, amber, orange, deep orange, brown, grey, blue grey
      accent: 'deep orange'
    font:
      text: 'Segoe Print'   # 'Kristen ITC' 'Roboto' 'Segoe Print' 'Tempus Sans ITC' 
      code: 'Consolas'      # 'Roboto Mono' 'Consolas'
    logo: 'cogs.png'        #'ivor24.png'   'logo.svg'
    social:                 # see: http://fontawesome.io/icons/
      - type: 'slack'
        link: 'https://uklabsid.slack.com'
      - type: 'stack-overflow'
        link: 'http://stackoverflow.com'
      - type: 'youtube'
        link: 'https://www.youtube.com/user/IBM'
      - type: 'telegram'
        link: 'https://www.telegram.org/'
      - type: 'whatsapp'
        link: 'https://www.whatsapp.com/'
      - type: 'comment-o'
        link: 'mailto:me@uk.ibm.com?subject=MkDocs play'
      - type: 'facebook'
        link: 'https://www.facebook.com/IBM/'
      - type: 'github'
        link: 'https://github.com/pmhayward/mkd-test'
      - type: 'twitter'
        link: 'https://twitter.com/IBM'
      - type: 'linkedin'
        link: 'https://www.linkedin.com'

pages:
    - Home: index.md

    - Stuff:
        - Test tags                                                  : test_tags_190.md
        - MkDocs notes                                               : mkdocs_notes.md
        - Conversion process                                         : conversion.md
        - Pandoc transforms                                          : transforms.md


    - Lorem 1: lorem001.md
    - Lorem A:
        - Lorem 2: lorem002.md
        - Lorem 3: lorem003.md
    - Lorem B:
        - Lorem 4: lorem004.md
        - Lorem 5: lorem005.md
        - Lorem C:
            - Lorem 6: lorem006.md
            - Lorem 7: lorem007.md
            - Lorem D:
                - Lorem 8: lorem008.md
                - Lorem very long title with lots of words:
                    - Lorem 8: lorem008.md
                    - Lorem very long title with lots of words:
                        - Lorem 8: lorem008.md
                        - Lorem very long title with lots of words:
                            - Lorem 8: lorem008.md
                            - Lorem very long title with lots of words:
                                - Lorem 8: lorem008.md
                                - Lorem very long title with lots of words:
                                    - Lorem 8: lorem008.md
                - Lorem 9: lorem009.md
    - Lorem 10: lorem010.md

